steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devtest', '.']

  # Step 2: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'DevTest'
      - '--image'
      - 'gcr.io/$PROJECT_ID/devtest'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    

# Optional: Specify images in build artifacts for logging
images:
  - 'gcr.io/$PROJECT_ID/devtest'
